-- Speed HUD layout. The movement controller never positions UI.

return {
	Position = UDim2.fromScale(0.5, 0.78),
	SpeedTextSize = 48,
	DetailTextSize = 18,
	Font = Enum.Font.GothamBold,
	Color = Color3.fromRGB(255, 255, 255),
	AirColor = Color3.fromRGB(255, 196, 96),
	GroundColor = Color3.fromRGB(186, 230, 186),
	StrokeTransparency = 0.45,

	-- Live air-control sliders. Right Shift toggles the panel.
	AirTune = {
		Position = UDim2.fromScale(0.015, 0.16),
		Width = 300,
		Padding = 10,
		RowHeight = 64,
		TitleSize = 16,
		LabelSize = 13,
		ValueSize = 13,
		HintSize = 12,
		Font = Enum.Font.GothamBold,
		BodyFont = Enum.Font.Gotham,
		Background = Color3.fromRGB(16, 18, 22),
		BackgroundTransparency = 0.12,
		Track = Color3.fromRGB(58, 64, 74),
		Fill = Color3.fromRGB(255, 186, 84),
		Text = Color3.fromRGB(245, 245, 245),
		Muted = Color3.fromRGB(176, 182, 192),
		Title = "Air control",
		AnchorPoint = Vector2.new(0, 0),
		Hint = "Right Shift toggles both panels. Close them to look around.",
		Chip = "Right Shift - tune",
		Sliders = {
			{
				id = "AirAccelerate",
				label = "Air accelerate",
				detail = "Turn rate. This is sv_airaccelerate.",
				min = 1,
				max = 24,
				step = 0.5,
				source = "movement",
			},
			{
				id = "AirSpeedCap",
				label = "Air speed cap",
				detail = "Max shove along the strafe. Lower keeps the line.",
				min = 1,
				max = 26,
				step = 0.5,
				source = "movement",
			},
			{
				id = "AirWishSpeed",
				label = "Air wish speed",
				detail = "Scales how fast the cap fills. Same axis as accelerate.",
				min = 8,
				max = 40,
				step = 1,
				source = "movement",
			},
			{
				id = "AirBrake",
				label = "Air brake",
				detail = "Speed lost when W fights your line. 0 keeps it.",
				min = 0,
				max = 1,
				step = 0.05,
				source = "movement",
			},
			{
				id = "WallFriction",
				label = "Wall friction",
				detail = "Speed lost while flush with a wall. 0 is ice.",
				min = 0,
				max = 24,
				step = 0.5,
				source = "movement",
			},
			{
				id = "Gravity",
				label = "Gravity",
				detail = "Air time. Higher falls faster.",
				min = 80,
				max = 280,
				step = 5,
				source = "movement",
			},
			{
				id = "JumpSpeed",
				label = "Jump speed",
				detail = "How long a normal hop stays in the air.",
				min = 30,
				max = 110,
				step = 1,
				source = "movement",
			},
			{
				id = "MouseSensitivity",
				label = "Mouse sensitivity",
				detail = "Look speed in play. Lower is slower.",
				min = 0.05,
				max = 2,
				step = 0.05,
				source = "mouse",
			},
		},
	},

	-- Live rocket sliders. Same Right Shift toggle as the air panel.
	RocketTune = {
		Position = UDim2.new(1, -12, 0.16, 0),
		AnchorPoint = Vector2.new(1, 0),
		Width = 300,
		Padding = 10,
		RowHeight = 64,
		TitleSize = 16,
		LabelSize = 13,
		ValueSize = 13,
		HintSize = 12,
		Font = Enum.Font.GothamBold,
		BodyFont = Enum.Font.Gotham,
		Background = Color3.fromRGB(16, 18, 22),
		BackgroundTransparency = 0.12,
		Track = Color3.fromRGB(58, 64, 74),
		Fill = Color3.fromRGB(255, 122, 64),
		Text = Color3.fromRGB(245, 245, 245),
		Muted = Color3.fromRGB(176, 182, 192),
		Title = "Rocket",
		Hint = "Blast adds to the speed you already have.",
		Sliders = {
			{
				id = "ExplosionForce",
				label = "Explosion force",
				detail = "How hard the blast shoves you.",
				min = 40,
				max = 600,
				step = 10,
				source = "rocket",
			},
			{
				id = "ExplosionRadius",
				label = "Explosion radius",
				detail = "Reach of the shove. The edge is zero.",
				min = 6,
				max = 36,
				step = 1,
				source = "rocket",
			},
			{
				id = "SelfForceMultiplier",
				label = "Self multiplier",
				detail = "Extra force on you, the shooter.",
				min = 0.5,
				max = 3,
				step = 0.05,
				source = "rocket",
			},
			{
				id = "SelfUpBias",
				label = "Upward bias",
				detail = "Lift from a blast near you. 0 is the raw angle.",
				min = 0,
				max = 8,
				step = 0.25,
				source = "rocket",
			},
			{
				id = "RocketSpeed",
				label = "Rocket speed",
				detail = "How fast the shot travels.",
				min = 40,
				max = 400,
				step = 10,
				source = "rocket",
			},
			{
				id = "Cooldown",
				label = "Cooldown",
				detail = "Seconds before the next shot.",
				min = 0.1,
				max = 2,
				step = 0.05,
				source = "rocket",
			},
		},
	},

	Timer = {
		Position = UDim2.fromScale(0.5, 0.03),
		TextSize = 36,
		BestSize = 16,
		Font = Enum.Font.GothamBold,
		Color = Color3.fromRGB(255, 255, 255),
		BestColor = Color3.fromRGB(176, 182, 192),
		BestImproved = Color3.fromRGB(120, 255, 170),
	},

	TargetCount = {
		Position = UDim2.fromScale(0.5, 0.115),
		TextSize = 22,
		HintSize = 14,
		Font = Enum.Font.GothamBold,
		Color = Color3.fromRGB(186, 230, 186),
		OpenColor = Color3.fromRGB(120, 255, 170),
		HintColor = Color3.fromRGB(176, 182, 192),
		Hint = "R resets the run. N next map",
	},

	CourseBanner = {
		Position = UDim2.fromScale(0.5, 0.18),
		TextSize = 42,
		Font = Enum.Font.GothamBold,
		Color = Color3.fromRGB(190, 255, 210),
		Text = "0.00",
		Seconds = 2.5,
	},

	Crosshair = {
		Enabled = true,
		Size = 5,
		Color = Color3.fromRGB(255, 255, 255),
		Transparency = 0.15,
	},

	Leaderboard = {
		Position = UDim2.new(1, -16, 0.18, 0),
		AnchorPoint = Vector2.new(1, 0),
		Width = 230,
		Padding = 10,
		RowHeight = 18,
		TitleSize = 16,
		RowSize = 14,
		MaxRows = 8,
		Font = Enum.Font.GothamBold,
		BodyFont = Enum.Font.Gotham,
		Text = Color3.fromRGB(245, 245, 245),
		Muted = Color3.fromRGB(176, 182, 192),
		You = Color3.fromRGB(120, 255, 170),
		Background = Color3.fromRGB(16, 18, 22),
		BackgroundTransparency = 0.28,
	},
}
